spring.application.name=suncomputer

# ==========================================
# SERVER
# ==========================================

server.port=8080

# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password= 1234

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# FLYWAY
# ==========================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# ==========================================
# LOGGING
# ==========================================

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# ==========================================
# JWT
# ==========================================

app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_FOR_PRODUCTION_123456789
app.jwt.expiration=86400000